config/routes.rb
Rails.application.routes.draw do
  root to: 'communities#index'
  resources :communities, only: %i[index new create show] do
    resources :comments, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :community
end

app/models/community.rb
class Community < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_community

  def new
    @comment = @community.comments.new
  end

  def create
    @comment = @community.comments.new(comment_params)
    if @comment.save
      redirect_to community_path(@community)
    else
      render :new
    end
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def comment_params
    params.require(:comment).permit(:author_name, :content)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  def show
    @community = Community.find(params[:id])
    @comments = @community.comments.order(created_at: :desc) # 投稿日：降順で並び替え  
  end

  private

  def community_params
    params.require(:community).permit(:title, :owner_name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/comments/new.html.haml
= link_to community_path(@community), class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', community_title: @community.title)
  = form_with model: [@community, @comment] do |form|
    = form.label :author_name, class: 'form-label'
    = form.text_field :author_name, class: 'form-control mb-2'
    = form.label :content, class: 'form-label'
    = form.text_area :content, class: 'form-control mb-4'
    = form.submit '投稿', class: 'btn btn-primary'

app/views/communities/create.html.haml
%h1 Communities#create
%p Find me in app/views/communities/create.html.erb

app/views/communities/index.html.haml
.d-flex.justify-content-between.align-items-center.mb-4
  %h1= t('.title')
  = link_to new_community_path, class: 'btn btn-primary' do
    %i.fas.fa-plus
    = t('.link_to_new')

.container-fluid
  .row
    - @communities.each do |community|
      .col-md-6.col-lg-4.p-1
        .card
          .card-body
            %h4= community.title
            %div= t('activerecord.attributes.community.owner_name') + '：' + community.owner_name
            .d-flex.justify-content-between
              %div= t('activerecord.attributes.community.created_at') + '：' + l(community.created_at)
              = link_to community_path(community) do
                %i.fas.fa-arrow-right
                中に入る

app/views/communities/new.html.haml
%h1= t('.title')
= form_with model: @community do |form|
  = form.label :title, class: 'form-label'
  = form.text_field :title, class: 'form-control mb-2'
  = form.label :owner_name, class: 'form-label'
  = form.text_field :owner_name, class: 'form-control mb-4'
  = form.submit '作成', class: 'btn btn-primary'

app/views/communities/show.html.haml
= link_to communities_path, class: 'btn btn-light mb-3' do
  %i.fas.fa-arrow-left
  戻る

.container
  %h1= t('.title', title: @community.title)
  = link_to new_community_comment_path(@community), class: 'btn btn-primary' do
    %i.fas.fa-comment
    = t('.link_to_new_comment')

  %ul.list-group.mt-4
    - @comments.each do |comment|
      %li.list-group-item
        .fs-5= comment.author_name
        .fs-6.mb-3= l(comment.created_at, format: :long)
        .fs-6= simple_format(comment.content)

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to root_path, class: 'navbar-brand' do
      Rails6.1掲示板
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to root_path, class: 'nav-link' do
            トップ
        %li.nav-item
          = link_to new_community_path, class: 'nav-link' do
            コミュニティを作る

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails61HandsOn
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render '/layouts/header'
    .container-fluid.pt-4.px-4
      = yield